#! /bin/bash
board_name=$(cat /sys/class/dmi/id/board_name)
if [[ "$board_name" == "Jupiter" || "$board_name" == "Galileo" ]] then
    kwriteconfig6 --file /etc/xdg/kdeglobals --group KDE --key LookAndFeelPackage "com.valve.vapor.deck.desktop"
fi
